---
title: "CV"
description: |
  Current CV
---
Education
======
* University of California, Santa Barbara (UCSB)
  * Ecology Evolution, and Marine Biology
  * Ph.D. in 2026
* University of California, Davis (UCD)
  * Bachelor of Science in Biological Sciences

Work Experience
======
* 2018 – 2020
  * UC Davis, Department of Animal Science, PI: Prof. Anne Todgham
    *Laboratory and Field Technician: American River Chinook Salmon Survival in Relation to Redd Water Quality: The Role of Spatial and Temporal Variability 
    * Laboratory Technician: DNA barcoding early life stages of Antarctic fishes
    * Undergraduate Researcher: Critical windows of stress tolerance during Chinook salmon development
    * Undergraduate Researcher: RNAseq sample preparation for California mussels 
* 2019
  * UC Davis Coastal and Marine Sciences Institute, Bodega Marine Laboratory, Bodega Bay, CA             *Undergraduate Researcher: Effects of a record-breaking heatwave on mussel bed communities in northern California 
* 2018	
  * UC Santa Barbara Marine Science Institute, University of California, Santa Barbara, PI: Prof. Gretchen Hofmann
    *Summer Undergraduate Researcher: Physiological and molecular assessment of thermal tolerance of Lytechinus pictus 
* 2016 – 2018	
  * UC Davis, Department of Pharmacology, PI: Profs. Donald Bers and Julie Bossuyt
	  *Undergraduate Researcher: Interactome Analysis of CaMKIIδ in Cardiac Myocytes Using a Proximity Labeling Approach


